Heap
void Heap::flotar(std::vector< int > &arr, int pos)
Referenced by crear_heap.
void Heap::hundir(std::vector< int > &arr, int pos)
Referenced by ordenar_heap.
void Heap::crear_heap(std::vector< int > &array)
References flotar.
Referenced by bottomk_element, nlargest, nsmallest, topk_element.
void Heap::ordenar_heap(std::vector< int > &array)
References hundir.
Referenced by bottomk_element, nlargest, nsmallest, topk_element.
std::vector< int > Heap::nlargest(int n, std::vector< int > array)
References crear_heap, ordenar_heap.
std::vector< int > Heap::nsmallest(int n, std::vector< int > array)
References crear_heap, ordenar_heap.
int Heap::topk_element(int n, std::vector< int > array)
References crear_heap, ordenar_heap.
int Heap::bottomk_element(int n, std::vector< int > array)
References crear_heap, ordenar_heap.